### PR TITLE
Refactor and rewrite

### PR DESCRIPTION
**Pull request by yp2**
Refactor and rewrite of component base on angular cli project. npm packege with ng-packagr. Builds with aot. Added proper handling of ControlValueAccessor on wirteValue. Inner form build with reactive forms.

### CODE REVIEW

**Comment by rvalenciano** [comment]
Hi @yp2 , thanks for contributing, today I'll setup this locally and if everything is ok, merge it

**Comment by rvalenciano** [comment]
Hey @yp2 can you send me an email (to ravf.226@gmail.com) to add you as contributor in the original project? Also I can help you with some of the pending issues you registered in the fork.

**Comment by yp2** [comment]
Hi, use my GitHub profile.

**Comment by rvalenciano** [comment]
Ok, can you rebase your fork with my master? I added travis ci and code climate, maybe you should also set them up in case we continue using your repo in your profile.

**Comment by yp2** [comment]
Yes I will do that.

**Pull request merged**
